name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "NX_BASE=$(git rev-parse origin/$GITHUB_BASE_REF)" >> $GITHUB_ENV
      - run: echo "NX_HEAD=$(git rev-parse origin/$GITHUB_HEAD_REF)" >> $GITHUB_ENV
      - run: echo "base=$NX_BASE head=$NX_HEAD"
      - run: npm ci
      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=build --parallel=3
